name: claude-review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  context:
    name: Build review context
    runs-on: ubuntu-latest
    outputs:
      summary: ${{ steps.summarize.outputs.summary }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

  review:
    needs: context
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          direct_prompt: |
            ${{ needs.context.outputs.summary }}

            Review this pull request and provide feedback on:
            - overall correctness and architectural alignment across touched scopes
            - code quality and best practices
            - potential bugs, regressions, and data consistency issues
            - performance, security, and observability concerns
            - test coverage or missing validation paths

            Always reference the WHY.md and the README.me to align priorities/goals